CREATE TABLE DIM_DATES (
DATE_ID INT NOT NULL,
FULL_DATE DATETIME NOT NULL,
DAY_NAME VARCHAR(10) NOT NULL,
DAY NUMERIC(2) NOT NULL,
MONTH_NAME VARCHAR(12) NOT NULL,
MONTH NUMERIC(2) NOT NULL,
YEAR NUMERIC(4) NOT NULL,
DAY_OF_MONTH NUMERIC(2) NOT NULL,
DAY_OF_WEEK NUMERIC(1) NOT NULL,
DAY_OF_YEAR NUMERIC(3) NOT NULL,
DAY_OF_QUARTER NUMERIC(2),
MONTH_OF_YEAR NUMERIC(2) NOT NULL,
MONTH_OF_QUARTER NUMERIC(1),
DDMMYYYY VARCHAR(8) NOT NULL,
MMDDYYYY VARCHAR(8) NOT NULL,
PRIMARY KEY (DATE_ID)
);

