CREATE TABLE DIM_CUSTOMERS (
CUSTOMER_ID INT NOT NULL,
FIRST_NAME VARCHAR(30) NOT NULL,
LAST_NAME VARCHAR(30) NOT NULL,
DATE_OF_BIRTH DATE NOT NULL,
GENDER CHAR(1) NOT NULL,
ADDRESS_LINE_1 VARCHAR(50) NOT NULL,
ADDRESS_LINE_2 VARCHAR(50),
CITY VARCHAR(30) NOT NULL,
STATE VARCHAR(30) NOT NULL,
ZIP_CODE VARCHAR(10) NOT NULL,
COUNTRY VARCHAR(100) NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
PHONE DECIMAL(10) NOT NULL,
PRIMARY KEY (CUSTOMER_ID)
);