CREATE TABLE FACT_ORDERS (
ORDER_ID INT NOT NULL,
STORE_ID INT FOREIGN KEY REFERENCES DIM_STORES(STORE_ID),
PRODUCT_ID INT FOREIGN KEY REFERENCES DIM_PRODUCTS(PRODUCT_ID),
CUSTOMER_ID INT FOREIGN KEY REFERENCES DIM_CUSTOMERS(CUSTOMER_ID),
DATE_ID INT FOREIGN KEY REFERENCES DIM_DATES(DATE_ID),
QUANTITY INT NOT NULL,
TOTAL_AMOUNT DECIMAL(10,2) NOT NULL,
PRIMARY KEY (ORDER_ID)
);